#!/bin/sh

action="$1"
workspace="$2"

focused_workspace=$(i3-msg -t get_workspaces |\
    jq --raw-output '.[]|select(.focused).num')

if [ "$focused_workspace" -le 10 ]
then
    target_workspace=${workspace}
else
    target_workspace=$((10 + workspace))
fi

if [ "$action" = "move" ]; 
then
    i3-msg "move container to workspace number $target_workspace"\
        && i3-msg "workspace number $target_workspace"
else
    i3-msg "workspace number $target_workspace"
fi
