#!/bin/sh
while read file
do
    case "$1" in
        "w") setbg "$file" & ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] &&
                rm "$file" && notify-send "$file deleted." ;;

        "y")
            echo -n "$file" | xclip -selection clipboard &&
                notify-send "$file copied to clipboard" & ;;
        "Y")
            echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;

        "b") 
            newfile="$(dirname "$file")/$(dmenu -p "New file name: " <&-).${file##*.}"
            mv "$file" "$newfile"
            wpg -a "$newfile" && wpg -s "$newfile"
            ;;
    esac
done
