#!/bin/sh

# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

killall dunst || true

dunst \
    -lb "${color0:=#F0F0F0}" \
    -nb "$color0" \
    -cb "$color0" \
    -lf "${color8:=#000000}" \
    -bf "$color8" \
    -cf "$color8" \
    -nf "$color8" &
