#!/usr/bin/env python3

import gi
gi.require_version('Playerctl', '2.0')
from gi.repository import Playerctl, GLib
import requests
from pathlib import Path
import os

cover_file = f'{Path.home()}/.cache/cover.jpg'


def on_track_change(player, e):
    url = e['mpris:artUrl']
    r = requests.get(url, allow_redirects=True)
    open(cover_file, 'wb').write(r.content)


player = Playerctl.Player()
player.connect('metadata', on_track_change)
os.system(f'feh --title album-cover --zoom 80 --auto-reload {cover_file} &')

GLib.MainLoop().run()
