#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1"  ] && cp "$1" ~/.config/wall.png
# xwallpaper --maximize ~/.config/wall.png

xwallpaper --zoom ~/.config/wall.png
# xwallpaper --trim 1920x1080 --zoom ~/.config/wall.png
